const dailyData = {
    "main": {
        "kicker": "",
        "titleWhite": "MAERSK RAISES 2026 OUTLOOK",
        "titleBlue": "AGAIN",
        "footerSummary": "Maersk elevates full-year profit projections amid robust ex-Asia ocean demand, while freight operators navigate tightening peak season capacity constraints."
    },
    "slides": [
        {
            "id": 1,
            "heading": "MAERSK: RAISES 2026 OUTLOOK AGAIN",
            "points": [
                "A.P. Moller - Maersk upgraded its full-year 2026 financial guidance for the second consecutive quarter following sustained export volumes from Asia.",
                "The Danish shipping conglomerate reported stellar earnings growth across its ocean container division, outperforming broader market consensus.",
                "Sustained ocean freight demand and resilient freight rate environments continue to drive profitability across major carrier balance sheets.",
                "Global shippers should anticipate disciplined capacity management from carrier alliances entering the fourth-quarter peak season."
            ],
            "imageUrl": "",
            "nextUpTease": "TRADE COURT: DE MINIMIS SUSPENSION",
            "tags": [
                "Source: https://www.freightwaves.com",
                "Published: 2026-08-13T10:00:00Z",
                "Status: Audited & True"
            ]
        },
        {
            "id": 2,
            "heading": "TRADE COURT: DE MINIMIS SUSPENSION",
            "points": [
                "The U.S. Court of International Trade officially upheld the federal suspension of the low-value de minimis customs exemption.",
                "U.S. Customs and Border Protection reported over $1 billion in cumulative duty collections generated by the policy enforcement through late 2025.",
                "Cross-border e-commerce sellers and retail importers face permanent structural cost increases on direct-to-consumer parcel shipments.",
                "Supply chain compliance directors must integrate mandatory formal entry filings and duty accounting protocols for all inbound postal parcels."
            ],
            "imageUrl": "",
            "nextUpTease": "MARITIME: H-LINE TANKER SWAP",
            "tags": [
                "Source: https://www.ttnews.com",
                "Published: 2026-08-13T14:00:00Z",
                "Status: Audited & True"
            ]
        },
        {
            "id": 3,
            "heading": "MARITIME: H-LINE TANKER SWAP",
            "points": [
                "South Korea\u2019s SK Shipping finalized a 28-vessel asset swap with H-Line Shipping to double its active LNG carrier fleet to 32 ships.",
                "The strategic fleet restructuring positions SK Shipping to capture top-tier market share in Asian liquefied natural gas transport corridors.",
                "Private equity owner Hahn & Co orchestrated the complex vessel exchange to streamline operational focus amid growing energy demand.",
                "Global energy shippers will encounter tighter vessel availability and recalibrated charter rates across long-term LNG maritime routes."
            ],
            "imageUrl": "",
            "nextUpTease": "TRUCKING: NON-DOMICILED CDL LIMITS",
            "tags": [
                "Source: https://www.ttnews.com",
                "Published: 2026-08-13T09:30:00Z",
                "Status: Audited & True"
            ]
        },
        {
            "id": 4,
            "heading": "TRUCKING: NON-DOMICILED CDL LIMITS",
            "points": [
                "State transportation departments in Rhode Island and Utah enacted strict new limits on the issuance of non-domiciled commercial driver's licenses.",
                "Industry analysts project that nationwide foreign driver losses will exceed the federal estimate of 200,000 as additional states adopt restrictions.",
                "Over-the-road freight motor carriers face intensified driver recruitment deficits and localized fleet capacity reductions.",
                "Freight shippers should review carrier partner routing guides to mitigate rising spot rates and driver availability bottlenecks."
            ],
            "imageUrl": "",
            "nextUpTease": "AIR CARGO: EVAPORATING PEAK DEMAND",
            "tags": [
                "Source: https://www.ttnews.com",
                "Published: 2026-08-13T08:45:00Z",
                "Status: Audited & True"
            ]
        },
        {
            "id": 5,
            "heading": "AIR CARGO: EVAPORATING PEAK DEMAND",
            "points": [
                "Air freight forwarders noted unusually muted peak season air cargo activity, signaling softer European and transatlantic trade volumes in H2.",
                "Recent regulatory reforms eliminating duty-free tax breaks on low-value imports have fundamentally altered cross-border shipping behavior.",
                "Airlines and cargo carriers are adjusting flight schedules and aircraft allocations to counter the sudden drop in e-commerce parcel volume.",
                "Logistics managers can leverage softer air cargo rates to optimize expedited inventory replenishment before year-end surges."
            ],
            "imageUrl": "",
            "nextUpTease": "RAILROAD: STB MERGER SCRUTINY",
            "tags": [
                "Source: https://www.supplychaindive.com",
                "Published: 2026-08-13T11:15:00Z",
                "Status: Audited & True"
            ]
        },
        {
            "id": 6,
            "heading": "RAILROAD: STB MERGER SCRUTINY",
            "points": [
                "Six state attorneys general formally opposed the proposed Union Pacific and Norfolk Southern merger, calling projected competitive benefits insufficient.",
                "The opposition filing before the Surface Transportation Board highlights rising regulatory resistance against Class I rail consolidation.",
                "Rail shippers and industrial logistics directors voiced concerns over potential service degradation and reduced interline routing choices.",
                "The prolonged regulatory battle threatens to stall structural efficiency initiatives across North American intermodal rail networks."
            ],
            "imageUrl": "",
            "nextUpTease": "PORT INFRASTRUCTURE: LA-LB CLEAN PLAN",
            "tags": [
                "Source: https://www.logisticsmgmt.com",
                "Published: 2026-08-13T12:00:00Z",
                "Status: Audited & True"
            ]
        },
        {
            "id": 7,
            "heading": "PORT INFRASTRUCTURE: LA-LB CLEAN PLAN",
            "points": [
                "The ports of Los Angeles and Long Beach introduced a comprehensive clean air addendum funded by dedicated electric vehicle charging investments.",
                "The new environmental initiative builds directly upon the regional emissions reduction framework inked by maritime regulators late last year.",
                "Terminal operators and drayage motor carriers must accelerate fleet electrification schedules to comply with tightening port mandates.",
                "Supply chain planners should factor potential terminal congestion and charging infrastructure bottlenecks into West Coast drayage strategies."
            ],
            "imageUrl": "",
            "nextUpTease": "FINAL SLIDE",
            "tags": [
                "Source: https://www.joc.com",
                "Published: 2026-08-13T13:15:00Z",
                "Status: Audited & True"
            ]
        }
    ]
};